version: '3.8'

services:
  scraper:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
